/// Generated by AssetsRefGenerator on 2020/03/14
class Res {
  static const String tutorial_image_1 = "assets/images/tutorial_image_1.png";
  static const String tutorial_image_2 = "assets/images/tutorial_image_2.png";
  static const String tutorial_image_3 = "assets/images/tutorial_image_3.png";
}
